### PR TITLE
Security & miscellaneous bug fixes

### PR DESCRIPTION
**Pull request by agwells**
Hi Gregor!

I cleaned up some parts of the plugin as part of a code review for one of our clients. Here's the list of changes I've made. I haven't exhaustively tested these yet; just the Dropbox, Microsoft, and Google parts. But since the code I changed was identical across all the blocktypes, I copied the changes across into all of them.

Cheers,
Aaron

### CODE REVIEW

**Comment by agwells** [comment]
Hm, looks like this code change breaks the mimetype detection for Google docs exports. I'll see if I can correct that.

**Comment by agwells** [comment]
Okay, all done changing things. This one is ready to merge if you want. :)

**Comment by agwells** [comment]
Cheers for the merge, Gregor!

I had some more minor issues that I noticed, that I didn't have funding to implement. (The client could only fund security issues and high-severity bugs). So I've filed those as Github issues, so you can have them on record. :)

**Comment by anzeljg** [comment]
Thanks Aaron.

**Pull request merged**
